# Generated by Django 4.2.5 on 2023-11-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_rename_matricula_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='coordenador',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
