# Generated by Django 4.2.5 on 2023-11-16 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_curso_coordenador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_client', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=9)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.cidade')),
            ],
        ),
    ]
